extern char _binary_Resources_Images_Introduction_studios_png_start;
extern char _binary_Resources_Images_Introduction_studios_png_end;
static const char* studios_png = &_binary_Resources_Images_Introduction_studios_png_start;
static const size_t studios_png_size = &_binary_Resources_Images_Introduction_studios_png_end - &_binary_Resources_Images_Introduction_studios_png_start;

extern char _binary_Resources_Images_Introduction_studio_light_png_start;
extern char _binary_Resources_Images_Introduction_studio_light_png_end;
static const char* studio_light_png = &_binary_Resources_Images_Introduction_studio_light_png_start;
static const size_t studio_light_png_size = &_binary_Resources_Images_Introduction_studio_light_png_end - &_binary_Resources_Images_Introduction_studio_light_png_start;

extern char _binary_Resources_Images_Introduction_emotion0_1_png_start;
extern char _binary_Resources_Images_Introduction_emotion0_1_png_end;
static const char* emotion0_1_png = &_binary_Resources_Images_Introduction_emotion0_1_png_start;
static const size_t emotion0_1_png_size = &_binary_Resources_Images_Introduction_emotion0_1_png_end - &_binary_Resources_Images_Introduction_emotion0_1_png_start;

extern char _binary_Resources_Images_Introduction_emotion2_stay_png_start;
extern char _binary_Resources_Images_Introduction_emotion2_stay_png_end;
static const char* emotion2_stay_png = &_binary_Resources_Images_Introduction_emotion2_stay_png_start;
static const size_t emotion2_stay_png_size = &_binary_Resources_Images_Introduction_emotion2_stay_png_end - &_binary_Resources_Images_Introduction_emotion2_stay_png_start;

extern char _binary_Resources_Images_Introduction_emotion3_jump_png_start;
extern char _binary_Resources_Images_Introduction_emotion3_jump_png_end;
static const char* emotion3_jump_png = &_binary_Resources_Images_Introduction_emotion3_jump_png_start;
static const size_t emotion3_jump_png_size = &_binary_Resources_Images_Introduction_emotion3_jump_png_end - &_binary_Resources_Images_Introduction_emotion3_jump_png_start;

extern char _binary_Resources_Images_Introduction_emotion4_boom_png_start;
extern char _binary_Resources_Images_Introduction_emotion4_boom_png_end;
static const char* emotion4_boom_png = &_binary_Resources_Images_Introduction_emotion4_boom_png_start;
static const size_t emotion4_boom_png_size = &_binary_Resources_Images_Introduction_emotion4_boom_png_end - &_binary_Resources_Images_Introduction_emotion4_boom_png_start;
