extern char _binary_Resources_Images_Person_menu_person_menu_background_png_start;
extern char _binary_Resources_Images_Person_menu_person_menu_background_png_end;
static const char* person_menu_background_png = &_binary_Resources_Images_Person_menu_person_menu_background_png_start;
static const size_t person_menu_background_png_size = &_binary_Resources_Images_Person_menu_person_menu_background_png_end - &_binary_Resources_Images_Person_menu_person_menu_background_png_start;

extern char _binary_Resources_Images_Person_menu_custom_png_start;
extern char _binary_Resources_Images_Person_menu_custom_png_end;
static const char* custom_png = &_binary_Resources_Images_Person_menu_custom_png_start;
static const size_t custom_png_size = &_binary_Resources_Images_Person_menu_custom_png_end - &_binary_Resources_Images_Person_menu_custom_png_start;

extern char _binary_Resources_Images_Person_menu_integrated_png_start;
extern char _binary_Resources_Images_Person_menu_integrated_png_end;
static const char* integrated_png = &_binary_Resources_Images_Person_menu_integrated_png_start;
static const size_t integrated_png_size = &_binary_Resources_Images_Person_menu_integrated_png_end - &_binary_Resources_Images_Person_menu_integrated_png_start;
