extern char _binary_Resources_Images_Test_menu_test_background_py_png_start;
extern char _binary_Resources_Images_Test_menu_test_background_py_png_end;
static const char* test_background_py_png = &_binary_Resources_Images_Test_menu_test_background_py_png_start;
static const size_t test_background_py_png_size = &_binary_Resources_Images_Test_menu_test_background_py_png_end - &_binary_Resources_Images_Test_menu_test_background_py_png_start;
