extern char _binary___Resources_Images_Language_menu_py_png_start;
extern char _binary___Resources_Images_Language_menu_py_png_end;
static const char* python_png = &_binary___Resources_Images_Language_menu_py_png_start;
static const size_t python_png_size = &_binary___Resources_Images_Language_menu_py_png_end - &_binary___Resources_Images_Language_menu_py_png_start;
