extern char _binary___Resources_Images_Main_menu_menu_background_png_start;
extern char _binary___Resources_Images_Main_menu_menu_background_png_end;
static const char* menu_background_png = &_binary___Resources_Images_Main_menu_menu_background_png_start;
static const size_t menu_background_png_size = &_binary___Resources_Images_Main_menu_menu_background_png_end - &_binary___Resources_Images_Main_menu_menu_background_png_start;

extern char _binary___Resources_Images_Main_menu_menu_ice_png_start;
extern char _binary___Resources_Images_Main_menu_menu_ice_png_end;
static const char* menu_ice_png = &_binary___Resources_Images_Main_menu_menu_ice_png_start;
static const size_t menu_ice_png_size = &_binary___Resources_Images_Main_menu_menu_ice_png_end - &_binary___Resources_Images_Main_menu_menu_ice_png_start;

extern char _binary___Resources_Images_Main_menu_popingvini_png_start;
extern char _binary___Resources_Images_Main_menu_popingvini_png_end;
static const char* popingvini_png = &_binary___Resources_Images_Main_menu_popingvini_png_start;
static const size_t popingvini_png_size = &_binary___Resources_Images_Main_menu_popingvini_png_end - &_binary___Resources_Images_Main_menu_popingvini_png_start;

extern char _binary___Resources_Images_Main_menu_popingvinit_png_start;
extern char _binary___Resources_Images_Main_menu_popingvinit_png_end;
static const char* popingvinit_png = &_binary___Resources_Images_Main_menu_popingvinit_png_start;
static const size_t popingvinit_png_size = &_binary___Resources_Images_Main_menu_popingvinit_png_end - &_binary___Resources_Images_Main_menu_popingvinit_png_start;

extern char _binary___Resources_Images_Main_menu_sdatca_png_start;
extern char _binary___Resources_Images_Main_menu_sdatca_png_end;
static const char* sdatca_png = &_binary___Resources_Images_Main_menu_sdatca_png_start;
static const size_t sdatca_png_size = &_binary___Resources_Images_Main_menu_sdatca_png_end - &_binary___Resources_Images_Main_menu_sdatca_png_start;

extern char _binary___Resources_Images_Main_menu_title_png_start;
extern char _binary___Resources_Images_Main_menu_title_png_end;
static const char* title_png = &_binary___Resources_Images_Main_menu_title_png_start;
static const size_t title_png_size = &_binary___Resources_Images_Main_menu_title_png_end - &_binary___Resources_Images_Main_menu_title_png_start;

extern char _binary___Resources_Images_Main_menu_wardrobe_button_png_start;
extern char _binary___Resources_Images_Main_menu_wardrobe_button_png_end;
static const char* wardrobe_button_png = &_binary___Resources_Images_Main_menu_wardrobe_button_png_start;
static const size_t wardrobe_button_png_size = &_binary___Resources_Images_Main_menu_wardrobe_button_png_end - &_binary___Resources_Images_Main_menu_wardrobe_button_png_start;
