extern char _binary_Resources_Images_Loading_loading_background_png_start;
extern char _binary_Resources_Images_Loading_loading_background_png_end;
static const char* loading_background_png = &_binary_Resources_Images_Loading_loading_background_png_start;
static const size_t loading_background_png_size = &_binary_Resources_Images_Loading_loading_background_png_end - &_binary_Resources_Images_Loading_loading_background_png_start;
