extern char _binary___Resources_Images_Introduction_studios_png_start;
extern char _binary___Resources_Images_Introduction_studios_png_end;
static const char *blackfire_studio_png = &_binary___Resources_Images_Introduction_studios_png_start;
static const size_t blackfire_studio_png_size = &_binary___Resources_Images_Introduction_studios_png_end - &_binary___Resources_Images_Introduction_studios_png_start;

extern char _binary___Resources_Images_Introduction_emotion0_1_png_start;
extern char _binary___Resources_Images_Introduction_emotion0_1_png_end;
static const char *emotion0_1_png = &_binary___Resources_Images_Introduction_emotion0_1_png_start;
static const size_t emotion0_1_png_size = &_binary___Resources_Images_Introduction_emotion0_1_png_end - &_binary___Resources_Images_Introduction_emotion0_1_png_start;

extern char _binary___Resources_Images_Introduction_emotion2_stay_png_start;
extern char _binary___Resources_Images_Introduction_emotion2_stay_png_end;
static const char *emotion2_stay_png = &_binary___Resources_Images_Introduction_emotion2_stay_png_start;
static const size_t emotion2_stay_png_size = &_binary___Resources_Images_Introduction_emotion2_stay_png_end - &_binary___Resources_Images_Introduction_emotion2_stay_png_start;

extern char _binary___Resources_Images_Introduction_emotion3_jump_png_start;
extern char _binary___Resources_Images_Introduction_emotion3_jump_png_end;
static const char *emotion3_jump_png = &_binary___Resources_Images_Introduction_emotion3_jump_png_start;
static const size_t emotion3_jump_png_size = &_binary___Resources_Images_Introduction_emotion3_jump_png_end - &_binary___Resources_Images_Introduction_emotion3_jump_png_start;

extern char _binary___Resources_Images_Introduction_emotion4_boom_png_start;
extern char _binary___Resources_Images_Introduction_emotion4_boom_png_end;
static const char *emotion4_boom_png = &_binary___Resources_Images_Introduction_emotion4_boom_png_start;
static const size_t emotion4_boom_png_size = &_binary___Resources_Images_Introduction_emotion4_boom_png_end - &_binary___Resources_Images_Introduction_emotion4_boom_png_start;
