extern char _binary_Resources_Shrift_pixel_font_by_BLACKFIRE_otf_start;
extern char _binary_Resources_Shrift_pixel_font_by_BLACKFIRE_otf_end;
static const char* pixel_font_by_BLACKFIRE_otf = &_binary_Resources_Shrift_pixel_font_by_BLACKFIRE_otf_start;
static const size_t pixel_font_by_BLACKFIRE_otf_size = &_binary_Resources_Shrift_pixel_font_by_BLACKFIRE_otf_end - &_binary_Resources_Shrift_pixel_font_by_BLACKFIRE_otf_start;
